esphome:
  name: esp-boot
  includes:
    - custom_i2c.h

esp32:
  board: esp32-s3-devkitc-1
  framework:
    type: arduino

psram:
  mode: octal

logger:
  level: DEBUG

wifi:
  ssid: "FRITZ!Box 7590 JL"
  password: "28182272528993262336"

improv_serial:
captive_portal:

# Wir legen den offiziellen I2C-Bus auf ungenutzte Dummy-Pins,
# damit der IDF-Treiber die echten Leitungen (6 und 7) nicht blockieren kann!
i2c:
  id: bus_dummy
  sda: GPIO1
  scl: GPIO2

# Aktiviert unsere eigene I2C-Initialisierung direkt beim Start
custom_component:
  - lambda: |-
      auto my_custom_i2c = new CustomI2CInit();
      return {my_custom_i2c};

spi:
  - id: spi_bus
    clk_pin: GPIO47
    mosi_pin: GPIO41

# Den normalen pca9554-Block kommentieren wir aus, da wir ihn im C++-Code steuern
# pca9554:
#   - id: pca9554_hub
#     address: 0x20

display:
  - platform: ili9xxx
    id: display_lcd
    spi_id: spi_bus
    model: ST7796
    dimensions:
      width: 320
      height: 480
    data_rate: 40MHz
    invert_colors: false
    cs_pin: GPIO42
    dc_pin: GPIO45
    reset_pin: GPIO40
    rotation: 0°
    update_interval: 1s
    lambda: |-
      it.fill(Color(255, 0, 0));
