esphome:
  name: esp-boot
  friendly_name: ESP-Boot
  on_boot:
    priority: -100
    then:
      # Nutzt jetzt den nativen Switch-Befehl
      - switch.turn_on: backlight_switch
  includes:
    - my_components/custom_touch.h
    - my_components/custom_backlight.h

esp32:
  board: esp32-s3-devkitc-1
  framework:
    type: esp-idf

psram:
  mode: octal

logger:
  level: DEBUG

wifi:
  ssid: "FRITZ!Box 7590 JL"
  password: "28182272528993262336"

improv_serial:

captive_portal:

i2c:
  - id: bus_a
    sda: GPIO6
    scl: GPIO7
    frequency: 400khz
    scan: true

spi:
  - id: spi_bus
    clk_pin: GPIO47
    mosi_pin: GPIO41

pca9554:
  - id: pca9554_hub
    address: 0x20
    i2c_id: bus_a

# Das Backlight steuern wir jetzt über einen absolut standardkonformen Template-Switch!
switch:
  - platform: template
    name: "Backlight"
    id: backlight_switch
    optimistic: true
    turn_on_action:
      lambda: |-
        my_bl.set_pin_hub(id(pca9554_hub));
        my_bl.set_state(true);
    turn_off_action:
      lambda: |-
        my_bl.set_state(false);

display:
  - platform: ili9xxx
    id: display_lcd
    spi_id: spi_bus
    model: ST7796
    dimensions:
      width: 320
      height: 480
    data_rate: 40MHz
    invert_colors: false
    cs_pin: GPIO42
    dc_pin: GPIO45
    reset_pin: GPIO40
    rotation: 0°
    update_interval: 1s
    lambda: |-
      it.fill(Color(255, 0, 0));

# Um den Touchscreen beim Booten einmalig zu initialisieren, 
# hängen wir uns einfach stressfrei in eine native Boot-Komponente
interval:
  - interval: 60s
    then:
      - lambda: |-
          static bool initialized = false;
          if (!initialized) {
            auto touch = new CustomTouch();
            touch->setup();
            initialized = true;
          }
