name: ESPHome Compile

on:
  push:
    branches: [ main, develop ]
    paths:
      - '**.yaml'
      - 'my_components/**'
      - '.github/workflows/esphome-compile.yml'
  pull_request:
    branches: [ main ]
  workflow_dispatch:

# Hier fixen wir global die Node.js 24 Warnung für alle Schritte
env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: "true"

jobs:
  compile:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        
    - name: Cache PlatformIO & ESPHome
      uses: actions/cache@v4
      with:
        path: |
          ~/.platformio
          ~/.cache/pip
  
    
    - name: Install ESPHome
      run: pip install esphome
    
    - name: Compile ESP-Boot
      run: esphome compile esp-boot.yaml
    
    - name: Upload firmware artifact
      if: success()
      uses: actions/upload-artifact@v4
      with:
        name: firmware-esp-boot
        path: |
          .esphome/build/esp-boot/.pioenvs/esp-boot/firmware.factory.bin
          .esphome/build/esp-boot/.pioenvs/esp-boot/firmware.ota.bin
        retention-days: 30
